import { Geist, Geist_Mono } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import BootstrapClient from "./components/BootstrapClient";
import "./globals.css";
import AOSClient from "./components/AOSClient";
import { CartProvider } from "../context/CartContext";
import WhatsAppFloat from "./components/WhatsAppFloat";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
     <body>
  <BootstrapClient />
  <AOSClient />

  <CartProvider>
    {children}
    <WhatsAppFloat />
  </CartProvider>
  <Toaster
  position="top-right"
  toastOptions={{
    duration: 3000,
    style: {
      background: "#1f1f1f",
      color: "#fff",
      borderRadius: "14px",
      padding: "14px 18px",
    },
  }}
/>
</body>
    </html>
  );
}
